### ISSUE TITLE
DBCache is implemented in a non-efficient way

### ISSUE THREAD

**Issue by stof** [harikt/ghdocs#1]
`getModifiedSince` requires 2 SQL queries by itself.

and any request to github will trigger 3 queries before doing the request (2 for `getModifiedSince` and 1 for `getETag`), as well as a fourth one when the cache should be used (for `get`), all of them being the same.

**Comment by harikt** [comment]
Yes I will make the change :) .

Thank you @stof .

**Comment by harikt** [comment]
@stof I hope this will help. Let me know if you think it need any further change or not.

**Comment by harikt** [comment]
@stof do you think it is good to push to knplabs github-php-api the pdo cache ?

**Comment by stof** [comment]
well, a Redis, APC or Memcached based implementation would make more sense than PDO IMO for a cache. But I don't know what the Knp guys would think about merging this implementation in the API client itself. You should ask them (I provide review on the library, but I'm not a maintainer)

**Comment by harikt** [comment]
> well, a Redis, APC or Memcached based implementation would make more sense than PDO IMO for a cache

That makes sense. But I wonder how long the cache persists. I was thinking of if github fails can we get back the cache if it exists scenario ;) .

> I'm not a maintainer

I thought you were. Thank you.
